### ISSUE TITLE
Extension didn't work

### ISSUE THREAD

**Issue by Billy1900** [jounger/tinder-gold-seeker#1]
the goal `Let you see what you can't see` didn't really work, how can I make it work?

**Comment by jounger** [comment]
How to use?
Step 1: Go to "chrome://extensions/" then turn on "Developer mode".
Step 2: Click on "Load unpacked" button and select "tinder-gold-seeker" folder.
Step 3: Go "http://tinder.com/" and enjoy!

**Comment by Billy1900** [comment]
yes, I tried as your instructions in `readme.md`, but I still didn't see what I can not see such as `https://tinder.com/app/likes-you`

**Comment by jounger** [comment]
Maybe you have no one swipe right at that moment!
So you can not see anything.

**Comment by Billy1900** [comment]
what do you mean? I just wanna see `who likes me`, and it told me there are 4. you mean I can not see it?

**Comment by jounger** [comment]
Oh, I can't be clear how it works for you. But in my group (Tinder VietNam), almost people tried and it worked perfectly.
Try to join this group: https://www.facebook.com/groups/600239500420447/
Then read the instructions in this post: https://www.facebook.com/groups/600239500420447/permalink/838219909955737/

**Comment by Billy1900** [comment]
all right, Thx.
